### ISSUE TITLE
Branchname typo?: fsimx6sx-2024.01 <=> fsimx6sx-B2024.01

### ISSUE THREAD

**Issue by brenkem** [FSEmbedded/linux-fus#1]
Does the tag "fsimx6sx-2024.01" belong to the buildroot release or is it generic (see {1})?
Just for understanding, because the buildroot releases where marked with a "Byyyy.mm". But not in this case.

Thanks.

{1}:
…
fsimx6sx-2024.01
fsimx6sx-B2019.11
fsimx6sx-B2019.11.1
…

**Comment by Gerbach** [comment]
Hello,
yes we are trying to move to more generic version tag names for Kernel and Uboot because the same versions could get used in different releases. 
We could still tag the Buildroot and Yocto Release, where this Kernel version was used, as a light tag if this would be helpful to you.
In the future, we plan to change the version names to something like <MainlineVersion-F&SVersion>
For Linux Kernel this could be something like
v5.15.131-FS1.0
For Uboot something like
2023.04-FS1.0

What do you think of that?

**Comment by brenkem** [comment]
Okay. No need to change. Looks good. Thanks for the info.

Done.
